apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sit-mapping

namespace: sit
resources:
  - namespace.yaml
  - ../../base/api

patchesStrategicMerge:
  - override.yaml
